// ─── XERT Fitness membership terms and conditions ────────────────────────────
// The signed agreement, transcribed from the Word document the club has used on
// paper. This module is the single source of truth: the public agreement page
// renders it, and the digital acceptance form at /forms/terms-and-conditions is
// built from it, so the wording a member accepts is always the wording on the
// website. The membership options table was an image in the Word file and is
// transcribed as text here so it is readable on a phone and by screen readers.

export const XERT_TERMS_UPDATED = '5 September 2026';

export const XERT_TERMS_INTRO = 'This terms and conditions agreement is between Xert Fitness and the new member/client. These terms and conditions are effectively in place from the date this agreement is signed.';

export const XERT_TERMS_SECTIONS = Object.freeze([
  {
    id: 'tc-01-1-terms-conditions',
    title: '1. Terms & Conditions',
    content: [
      'To ensure that Xert Fitness is able to provide a safe and comfortable environment for all members and staff, please assist us by complying with the following conditions. We advise you to only sign this Agreement if you understand and agree to abide with these conditions. The information outlined in these terms and conditions can and will be used in the event of a discrepancy.',
    ],
  },
  {
    id: 'tc-02-2-introduction',
    title: '2. INTRODUCTION',
    content: [
      'By signing the Agreement, you acknowledge and agree:',
      '• You have been given a copy of this Agreement and agree to abide by your obligations in it;',
      '• You are medically sound to undertake a normal course of exercise, you use the Club facilities at your sole risk and responsibility and you are aware that exercise is physically demanding and participation in some activities offered by XERT may pose a risk to your health; and',
      '• This Agreement also relates to your authority to any third party payment provider nominated by XERT from time to time to direct debit your nominated bank account or credit card for any instalments or fees due under the terms and conditions of Stripes BECS Direct Debit Payments Request and Services Agreement which can be accessed at time of sign up or via there website https://docs.stripe.com/payments/au-becs-debit As a member, you can use our Club in line with these terms and conditions, including the Club code.',
    ],
  },
  {
    id: 'tc-03-3-definitions',
    title: '3. DEFINITIONS',
    content: [
      '• Xert, XERT Fitness, We, Us, Our: XERT Fitness ABN 65 327 079 634 Shop 14/15 27-31 Pound St, Kingaroy, QLD, 4610',
      '• You, Your, Member: You, Your, Member refers to the name in which the membership has been created, which at times may differ to the party paying for the membership, and includes the parent or guardian of the Member if the Member is under 18 years.',
      '• Club, Fitness Facility, Functional Gym and Home Club: Make reference to XERT Fitness Gym.',
      '• Agreement: This is the Agreement between Xert Fitness and you, under which you will become a member of XERT Fitness.',
      '• Minimum Term: The term specified in the Agreement form.',
      '• Code: Code for operating equipment, opening hours and behaviour in the Club, specified in these terms and conditions and some also displayed in Club signs.',
      '• Third Party Payment Provider: is the third party payment provider nominated by Xert from time to time, currently being Stripe Payments Pty Ltd at 1 Susexx Street, Barangaroo, Sydney NSW 2000, Australia, E-mail: support@stripe.com.',
      '• Website: “Website” means the XERT Fitness website at https://www.xertfitness.com.au',
      '• Supply Period: The supply period for a periodic agreement is the Minimum Term and is a minimum of two weeks.',
      '• Periodic Agreement: The membership is for the supply of the prescribed goods and services on an ongoing basis and will continue until terminated by you or Xert Fitness.',
      '• Upfront Membership: The membership is a Fixed Term Agreement paid for in totality upon commencement of the Agreement.',
      '• Access Pass: Digital Access via phone app',
    ],
  },
  {
    id: 'tc-04-4-memberships-available',
    title: '4. MEMBERSHIPS AVAILABLE',
    content: [
      'This section constitutes an Agreement summary for understanding our membership options: We note that this Agreement is subject to a cooling-off period, as outlined in clause 18 of these terms and conditions.',
      'Members can upgrade their membership type at their own discretion on their own time through the Fitbox app. Xert Fitness advises that you read over the information regarding the new membership type you are looking to change to and agree to the terms. If you have questions before upgrading / changing your membership type you need to contact Xert Fitness via email info@xertfitness.com.au and have these questions answered and understood before confirming the upgrade / change.',
      'The following access benefits apply to members who join on or after 5.9.26:',
      'XERT FITNESS MEMBERSHIP OPTIONS',
      '• Full Access Membership — $39 per week. Access to all XERT Fitness classes. Access to the training equipment during operational hours. Access to the Club for Personal Training sessions with your assigned Personal Trainer.',
      '• Full Access Membership, Sign Up Day offer only — $35.90 per week. Access to all XERT Fitness classes. Access to the training equipment during operational hours. 4 day Membership through foundational period to classes. Offer remains valid when renewing. This Membership price will not be carried over if the membership is to be cancelled.',
      '• Training with Personal Trainer, non members — $15.60 per week. Access to facility under guided coach. No access to classes.',
      '• Three Day Pass Visit — $35.90. Access to the Club for three trading days. Access to the Club and all classes over these three days only. Access to the training equipment during operational hours.',
      '• Casual Visit — $15.60. Access to the Club and all classes for that one day only. Access to the training equipment during operational hours.',
      '• Upfront 3 Months, Sign Up Day offer only — $400. Payment in full upfront. Membership ends after the 3rd month. Access to all XERT Fitness classes. Access to the training equipment during operational hours. Access to the Club for Personal Training sessions with your assigned Personal Trainer. Offer remains valid when renewing membership. This Membership price will not be carried over if membership is to be cancelled.',
      '• Upfront 3 Months — $468. Payment in full upfront. Membership ends after the 3rd month. Access to all XERT Fitness classes. Access to the training equipment during operational hours. Access to the Club for Personal Training sessions with your assigned Personal Trainer.',
      'Note: Your fees may change in line with any government GST rate changes if you sign up for a membership on the 30th of June and the payment comes out the following day on the 1st of July for example. Membership cancellations are permitted within 48 hours of Sign Up and no reason is required. Members are entitled to full refund provide the facility has not been used. Refer to 18. Cancellation / Termination as part of the Terms and Conditions on the website.',
    ],
  },
  {
    id: 'tc-05-3-queries',
    title: '3. QUERIES',
    content: [
      '• All queries and comments about the services provided under this Agreement should be directed to Xert Fitness via the contact details listed on our website.',
      '• All queries and comments about the direct debit billing service should be directed to Fit Box and Stripe.',
      '• Where the member elects to pay by way of direct debit, the member acknowledges that Stripe via Fix Box has been engaged by Xert Fitness to collect the fees due under this Agreement and the member further acknowledges that the member’s contractual relationship with Fix Box and Stripe is separate to this Agreement.',
    ],
  },
  {
    id: 'tc-06-5-club-access',
    title: '5. CLUB ACCESS',
    content: [
      'All members and those training with a personal trainer only, must sign in to the fitbox app and present their access pass (screen shots not accepted) upon entry to the Club at the start of every visit. If you attempt to enter the Club without your access pass Xert staff will ask you further questions to verify evidence of your membership or may ask you to pay a casual visit fee. A record of sign in is required to be sighted for safety, security and insurance purposes. Your access pass to Xert Fitness is for your use only, you cannot lend your pass or allow anyone else to use it. Warnings via email and/or SMS will be issued to members whose passes are found to have been used by others, and at the discretion of the club owner, the individual’s membership might be cancelled. If',
      '5.1. All Non Members Training with a Personal Trainer are unable to access Xert Fitness facility in the absence of their personal trainer.',
      '5.2. All Casual visitors and Three Day Pass visitors to Xert Fitness, are required to complete the sign in register via the link provided electronically or if there is a technical outage, by paper through the club. Casual visitors must also complete the Pre-Exercise Questionnaire, Risk Warning and Participant Acknowledgement prior to being signed off as fit to train in the club. Casual visitors must comply with our general conditions of entry and Club code as contained in these terms and conditions.',
    ],
  },
  {
    id: 'tc-07-6-general-conditions-of-entry-club-code',
    title: '6. GENERAL CONDITIONS OF ENTRY & CLUB CODE',
    content: [
      'To assist us in maintaining a safe and comfortable environment for all members and staff, you are required to abide by the following conditions. Failure to abide by these conditions may result in the suspension or termination of your membership.',
      'ENTRY: Entry will be refused or you may be requested to leave the Club if: You are using abusive or threatening language or behaving in a threatening way; or You are under the influence of drugs or alcohol; or you instruct other members when Xert Fitness has not authorised you to do so; or You behave in another way that is considered by Xert Fitness to be risky, unsafe or seriously inappropriate.',
      'SMOKING: You are not permitted to smoke (cigarettes or e-cigarettes) inside the facility. If you must smoke, smoking outside on the front grass across from the building is permitted, buds are not to be left on the grass, please take these with you or put into the nearest bin and they need to be properly burnt out. No smoking is permitted in the car park directly in front of the club. Please follow the non-smoking signs.',
      'TAILGATING: You must not admit any unauthorised person access to the Club or to exclusive facilities within the Club, such as Kids Play Pen, Bag storage area or to use the bathroom. If Xert staff on duty do not notice the tailgating in the first instance, you will later be contacted by the club via SMS or email to advise Xert Fitness is aware of the tailgating and will request for more information. Xert Fitness will refer to this tailgating policy and communicate a reminder of the importance of member ship sign in, in line with the club’s health and safety policy. If you are found to have brought in the same or different people on multiple occasions your membership with Xert Fitness will be reviewed by the owner and possibly terminated.',
      'KIDS PLAY PEN: A room for parents or relatives to supervise children has been provided. Xert trainers and staff are not responsible for supervising children at any time and are not Child Care qualified. When using the bathroom or hand washing basin, those responsible for the children/children in question, need to go around the front cement path directly in front of the roller doors avoiding the front parking area and remain with the child/children at all times. Children are not to touch any of the exercise equipment.',
      'SUITABLE CLOTHES: All members and guests must wear suitable clothes and enclosed shoes in and around the club exercise areas. If members wear open toe shoes they will be asked to change to enclosed shoes or advised that due to health and safety, they will be unable to train in the premises at that time. Clothes with offensive images or inappropriate advertising are not permitted.',
      'TOWELS: You are required to use a clean towel when participating in classes and when exercising on gym equipment (including exercise mats) to maintain our hygiene and safety standards. You may be requested to cease training if you do not use a towel. Subject to availability, you may purchase a towel from the front desk.',
      'CAMERA USE: Marketing consent has been requested of Xert Fitness members although, not all members will agree and each member and Xert staff will not know off hand, if another member has consented. Xert Fitness best practice is that cameras are not to be used in the Club when a photo includes that of members in the background. Taking photos or videos of other members without their consent is a breach of our terms and conditions and Xert Fitnesses privacy policy. If you are found to have been taking photos of other members and they bring it to the clubs attention that they do not consent, you will be issue a warning via SMS and/or email. If you are found to have repeatedly breached Xert Fitness’s Terms and Conditions and Privacy Policy in this regard, your membership maybe suspended.',
      'PARKING: You park in the parking spaces provided around the club at your own risk. To the extent permitted by law, we are not liable for any loss or damage to your vehicle or its contents.',
      'PERSONAL TRAINING: Personal training services are available for an additional fee paid directly to the Personal Trainer. You must hold the ‘training with personal trainer only’ membership. Please contact the Club for more information or visit the website. Conducting personal training within Xert Fitness’s without being an approved personal trainer, may result in the cancellation of your membership.',
      'USING THE GYM WHILST A GROUP CLASS IS IN SESSION: You are unable to make use of equipment assigned for a group session that is happening in the future or is currently in session. Understanding if such equipment is assigned to the session or not will be determined by asking if it does not appear obvious to whether it s or not or if you are asked by an Xert Trainer to please not use the equipment as the equipment you are reaching for or currently using is to be, or has been, assigned to the group fitness class.',
      'Please be mindful that at peak times such as Saturday morning, that it is unlikely there will be a squat rack free and other equipment will be limited. Please organise your workout to accommodate this setting in the gym at this time if you must train then and are not in the group class being held. This also entails setting up your fitness work station outside of the group fitness assigned area and doing your best not to get in the way of members actively in the class in session as you move around the club.',
    ],
  },
  {
    id: 'tc-08-7-use-of-equipment',
    title: '7. USE OF EQUIPMENT',
    content: [
      'You are required to return equipment to their original state when you have finished, including:',
      '• Return weights and bars to their rack.',
      '• Return equipment to its storage location.',
      '• For the safety of you and others, please follow all equipment operating and safety instructions on the equipment.',
      '• If you are not sure of correct use or operation of equipment please seek assistance from a team member.',
      '• Please seek assistance from a team member if you are unfamiliar with the equipment or its safe and appropriate use.',
      'As a courtesy to other members, please use a clean towel when using equipment and keep phone calls to a minimum.',
    ],
  },
  {
    id: 'tc-09-8-pigeonholes-valuables-and-lost-property',
    title: '8. PIGEONHOLES, VALUABLES AND LOST PROPERTY',
    content: [
      '• Pigeonholes are available and are located behind the front desk, however, Xert Fitness staff are not responsible for providing security.',
      '• To the extent permitted by law, Xert Fitness staff are not responsible for any loss of, or damage to, personal property kept in the club. We recommend that you don’t leave items loose in the pigeonholes, kept your bag/s zipped up and that you avoid bringing valuables to the club.',
      '• The Club is unable to look after your personal possessions (keys and wallets for example) whilst you are in the Facility.',
      '• Bags are not permitted on the gym floor for safety reasons.',
      '• As lockers are cleared daily, personal items are not permitted to be stored in pigeonholes overnight. Any items that remain at the end of the day or items that have been handed into a team member, will be held for two weeks and then disposed of or donated to charity.',
    ],
  },
  {
    id: 'tc-10-9-membership-fee-increase',
    title: '9. MEMBERSHIP FEE INCREASE',
    content: [
      'All Memberships automatically go onto periodic agreements once the first two weeks have been reached. All club access types are subject to a membership/fee increase when the new financial year presents. This new amount TBA, will be direct debited two weeks following the notice given to you directly via SMS/email.',
    ],
  },
  {
    id: 'tc-11-10-membership-entitlements',
    title: '10. MEMBERSHIP ENTITLEMENTS',
    content: [
      'Membership at Xert Fitness entitles you to:',
      '• Attend as many training sessions as you wish in a given period, subject to any restrictions in your membership type relating to Club access outside of staffed hours.',
      '• Attend the facility with a Personal Trainer only refers to the member only being able to access the facility with the Personal Trainer they pay separate to Xert Fitness',
      '• Xert Fitness reserves the right to make changes to exercise equipment supplied at any time or the class fitness timetable at any time (i.e. alter class type, times and instructors).',
    ],
  },
  {
    id: 'tc-12-11-corporate-partnerships-tba',
    title: '11. CORPORATE PARTNERSHIPS - TBA',
    content: [
    ],
  },
  {
    id: 'tc-13-12-children',
    title: '12. CHILDREN',
    content: [
      'Minors between the ages of 14 to 17 years may be eligible for a membership subject to the following age policy and the following general terms and conditions:',
      '• The minor must comply with all safety requirements of the Club as communicated to the member from time to time;',
      '• The minor’s membership may be cancelled for any inappropriate behaviour, misuse of equipment or failure to comply with safety requirements;',
      '• The minor must comply with the applicable sections of the age policy;',
      '• All minors must leave the Club immediately once staffed hours have ended; and',
      '• All minors can only access the subject to the qualifications and exclusions listed in the age policy.',
    ],
  },
  {
    id: 'tc-14-12-1-age-policy',
    title: '12.1. AGE POLICY',
    content: [
      '• 14 years',
      '• Membership is not permitted only Training with personal trainer, Three day pass or Casual visit with the consent and signature of the minor’s parent/legal guardian.',
      '• The parent/legal guardian assumes legal responsibility for performance of the minor’s obligations under this Agreement.',
      '• The minor member must be accompanied by their parent, legal guardian, suitably qualified personal trainer or other approved exercise professional with parental, legal guardians consent.',
      '• Permitted usage for this age group is as follows and subject always to the above conditions:',
      '• Ineligible to attend any group fitness classes',
      '• Cardio equipment',
      '• Other equipment prescribed by a medical or exercise professional',
      '• Ineligible to engage in challenges',
      '• 15 years',
      '• Minors in this age group are eligible to purchase Training with Personal Trainer only, Three day pass or a Casual visit passes, provided that their parent or legal guardian attends the Club on first visit and signs as guarantor on the waiver.',
      '• The parent/legal guardian assumes legal responsibility for performance of the minor’s obligations under this Agreement.',
      '• Permitted usage for this age group is as follows and subject always to the above conditions:',
      '• All group classes',
      '• All challenges',
      '• Weight-based and cardio equipment subject to medical advice If given',
      '• 16 and 17 years',
      '• Full Access Membership, Training with Personal Trainer only, Three day pass or a Casual visit passes, are permitted only with the consent and signature of the minor’s parent or legal guardian/guarantor on the waiver and provided that they attend the Club on first visit with the minor.',
      '• The parent/legal guardian assumes legal responsibility for performance of the minor’s obligations under this Agreement.',
      '• Access is permitted during opening hours and the minor is not required to be accompanied by their parent or legal guardian.',
      '• All classes and equipment are available, subject to any medical advice.',
    ],
  },
  {
    id: 'tc-15-13-legal-responsibility',
    title: '13. LEGAL RESPONSIBILITY',
    content: [
      'MEETING YOUR RESPONSIBILITIES',
      '• Your responsibilities, including payment of membership fees, these do not depend on how often you use the Club.',
      '• You must tell us about anything that affects your membership, and any changes to your contact information and bank details.',
      '• You must inform us in advance and in writing if there are any risks to your health if you participate in fitness services and if required, seek approval from your Doctor or General Practitioner.',
      'PROMISING TO TAKE CARE',
      'You promise to:',
      '• Make sure that you know how to exercise safely, by asking if necessary;',
      '• Use your best endeavours to exercise safely; and',
      '• Not take valuables into the Club, even if you plan to keep them zipped up in your bag.',
      'DAMAGE & PERSONAL INJURY',
      'To the extent permitted by law, Xert Fitness excludes any liability to the member in Agreement, tort, statute or in any other way for any injury, damage or loss of any kind whatsoever (including, without limitation, any liability for direct, indirect, special or consequential loss or damage), sustained by the member and/or any other person, or for any costs, charges or expenses incurred by the member, arising from or in connection with this Agreement and/or the services/products provided by Xert Firness and/or any act or omission of Xert Fitness.',
      'OUTSIDE PROVIDERS (Personal Trainers Only and Fitness/Health Contractors) TBA',
    ],
  },
  {
    id: 'tc-16-14-special-conditions-for-certain-membership',
    title: '14. SPECIAL CONDITIONS FOR CERTAIN MEMBERSHIP TYPES',
    content: [
      '• If there are special conditions or benefits relating to your membership type, these will be either attached to your Agreement and/or displayed on the website and form part of your Agreement.',
      '• Discounts are not offered on memberships currently.',
    ],
  },
  {
    id: 'tc-17-15-renewing-or-cancelling-upfront-membership',
    title: '15. RENEWING OR CANCELLING UPFRONT MEMBERSHIPS',
    content: [
      'This term applies only to Upfront Memberships. When your Upfront Membership is due to end you can renew your Upfront Membership at the current membership rate as advertised by Xert Fitness at the time of your membership renewal. By renewing your Upfront Membership, you agree to the membership terms that apply at that time.',
      'If you wish to cancel your Upfront Membership for any reason indicated in Section 18, we will refund you 100% of the value of the unexpired term remaining on your Upfront Membership less any applicable cancellation/administrative fees as soon as practicable (and within 7 days of termination where legally required).',
    ],
  },
  {
    id: 'tc-18-16-overdue-fees-revocation-of-membership-ent',
    title: '16. OVERDUE FEES & REVOCATION OF MEMBERSHIP ENTITLEMENTS',
    content: [
      'If there are repeated failures to meet your payment obligations (other than through the fault of Xert Fitness or its payment provider) four weekly payments or equivalent time period or more, without prejudicing Xert Fitness’s rights to recover any overdue payments, your membership may be suspended or terminated by written notice via SMS or email to you from Stripe/Fitbox or Xert Fitness directly. Once you have not made a payment within the last 14 days, you will no longer be able to book into any group classes. All entitlements and entry into the club may be revoked if your account is in arrears equivalent to four weeks or one month’s worth of failed payments or more and you fail to resolve the debt after being provided reasonable notice.',
      'If your automatic direct debit reverses or is returned to us by your financial institution the following process will apply:',
      '• The Club will attempt to contact you about retrying the debit.',
      '• If the debit remains outstanding it will be processed by Fitbox within 14 days of the reversal with any late fees that apply ($6). There maybe additional fees the members bank puts on the failed payment/s. Xert Fitness it not responsible for any of these fees.',
      '• If you fail to pay us the four weekly payments or equivalent to this period, by the confirmed due date, we are entitled to refuse you entry to the Club.',
      '• If unpaid fees remain outstanding and after attempts by us to rectify the arrears, your membership may be forwarded to a third-party debt collector for further action.',
    ],
  },
  {
    id: 'tc-19-17-debt-collection',
    title: '17. DEBT COLLECTION',
    content: [
      'If paying by direct debit, upon default by you, regarding any obligation under this Agreement and failure to remedy the default after notification by Xert Fitness, you authorise Xert Fitness to notify any third-party debt collector of the default.',
    ],
  },
  {
    id: 'tc-20-18-cancellation-termination',
    title: '18. CANCELLATION / TERMINATION',
    content: [
    ],
  },
  {
    id: 'tc-21-18-1-cancellation-of-class-booking-by-the-me',
    title: '18.1. CANCELLATION OF CLASS BOOKING BY THE MEMBER',
    content: [
      'Members have up to 30 minutes before the class to remove their registration through the website / Fitbox app. Members are not to contact the club outside of this 30 minute window to advise of the cancelation. Xert staff are not required to document or take note of any members who communicate with them by any means outside of this 30 minute window unless the member struggles to use the service to cancel their booking due to technical difficulties. The member may have notified Xert in person or sent a message via the Instagram page @xert_fit, emailed info@xertfitness.com.au or have their friend / family member pass on the message. If this were to be the case, the Xert staff member would visit the timetable and individual members calendar booking on the website / Fitbox and remove this manually.',
      'If members notify Xert Fitness of a class cancellation within the 30 minutes prior to the commencement of the class they will not be penalised but unable to record this action through the website / Fitbox app. Where this is to be the case, members are required to contact Xert Fitness via email only notifying of their last minute cancellation. Members who cancel within this window will not be penalised. If this appears to be a repeated occurrence from a particular member and the member is taking up space from other members on the waitlist this member will contacted by Xert Fitness in relation to their behaviour and in extreme circumstances, their membership will be reviewed.',
    ],
  },
  {
    id: 'tc-22-18-1-cancellation-of-class-booking-by-the-cl',
    title: '18.1. CANCELLATION OF CLASS BOOKING BY THE CLUB',
    content: [
      'If Xert Fitness is unable to conduct a class scheduled for any reason, Xert Fitness and it’s staff reserve the right to cancel classes up to 30 minutes prior to the scheduled start time. The club will notify members in as many was as possible including via SMS or email. Xert Fitness is not required to reimburse any members for the cancelled class in any way, shape or form as there are other classes running through the week that can be attended in the class in questions place. Xert Fitness and it’s staff do their best to make sure classes run as planned and on time in advance.',
    ],
  },
  {
    id: 'tc-23-18-3-cancellation-termination-of-membership',
    title: '18.3. CANCELLATION / TERMINATION OF MEMBERSHIP',
    content: [
      'Cancellation is permitted 48 hours from the date the membership agreement is signed. After this Cooling Off period has been reached, members are required to pay two further weeks of their weekly membership cost (one fortnightly payment for fortnightly payment members or half of their monthly payment for those paying monthly).',
      'Payment is best provided through Fitbox, in principle, the method you have used to pay your membership with whether Credit, Debit card or Bank Withdrawal for example so this will carry on for a further two weeks. The Xert staff member handling your cancellation will record for your account to expire two weeks from the date you requested to cancel.',
      'When you request to Cancel / Terminate your membership with us, please always:',
      '• Give us your email address so we can confirm your request in writing; and keep a copy of your request.',
      'You may be liable for further damages for breach of contract if you terminate the Agreement in a manner not described in the Agreement.',
      'A cancellation request should be provided to the Club as follows:',
      '48 HOUR COOLING OFF PERIOD',
      '• If you have held your membership for less than 48 hours, you can provide written notice via email to info@xertfitness.com.au or SMS without needing to provide a reason',
      '• If you have not used the gym by way of training or attending a class, you are entitled to a full refund',
      '• If you have used the gym for training or have attended a class, you will be charged for this service falling under the Casual membership option of $15.60 and refunded the remainder you have paid less a 10% administration fee (Xert staff are to contact Fitbox directly to be able to refund a percentage of what the customer has paid, only the exact amount of the original transaction can be refunded through Fitbox)',
      '• The cooling off period applies to new memberships only and does not apply to renewals',
      '• The cooling off period starts from the date the Agreement is entered into (the date the Agreement is signed) and ends at close of 48 hours in following (in business days)',
      'XERT FITNESS MEMBERSHIPS ARE PERIODIC MEMBERSHIP AGREEMENTS',
      'You acknowledge that unless you provide notice of termination / cancellation two weeks in advance via email at info@xertfitness.com.au, your membership fees will continue to be deducted from your date of Sign Up.',
      'Xert Fitness is unable to take the further two weeks of payments to cancel in full on the day you request. Fitbox requires a date to be recorded and must take the remaining payments following the usually cycle until this date.',
      'BANKRUPTCY',
      'You may terminate your Agreement without paying the required two week cancellation fee, if you are bankrupt and asking you to pay this fee is not a suitable option regarding your financial circumstances. To terminate your Agreement for this reason, you must provide Xert Fitness with evidence of a Notification of Bankruptcy from the Australian Financial Security Authority (AFSA), confirming your bankruptcy.',
      'TERMINATION BY THE CLUB',
      'The club reserves the right to terminate this Agreement in any of the following circumstances:',
      '• You fail to abide by any of the criteria listed in the conditions of entry (posted on the wall in the club) after being notified of any failure;',
      '• You fail to abide by the obligations listed in this Agreement and the breach/non-compliance is incapable of remedy or you fail to remedy the breach/ non-compliance within 14 days of being notified by Xert Fitness or you continue to breach this Agreement;',
      '• If we reasonably believe that you have engaged in conduct that infringes on the health, safety or wellbeing of any other members or staff;',
      '• The temporary or permanent closure of the Club or;',
      '• To protect the health and safety of you or other members.',
      'In the event of a termination under this provision and where appropriate, Xert Fitness will refund to you a proportion of fees paid under any Upfront Membership representing the unused portion of the Agreement less any applicable cancellation fees.',
      'TERMINATION BY THE MEMBER',
      'Members are unable to cancel their own memberships at their discretion. This can only be done by an Xert staff member through the Fitbox app.',
      'Members are permitted to terminate this Agreement, without incurring a cancellation fee, in the following circumstances:',
      '• Where these terms and conditions are varied in accordance with clause 23 ‘Additional Safety Measures’ or a club code is changed and you are adversely affected by the change. For the avoidance of doubt however, changes to club timetables, facilities, equipment and hours of operation do not permit you to terminate this Agreement under this clause.',
      '• If we breach our obligations to you and we do not fix the breach in a reasonable time after you have told us about it in writing. We will refund you any membership fees you pay between the date of notification and the date on which we decide that we cannot fix the breach.',
    ],
  },
  {
    id: 'tc-24-19-membership-suspension-frezzing',
    title: '19. MEMBERSHIP SUSPENSION / FREZZING',
    content: [
      'PERMANENT SICKNESS OR PHYSICAL INCAPACITY',
      'Memberships will be eligible for freezing with sufficient evidence provided including medical certificate or proof of travel documents. Xert staff will be responsible for freezing/suspending as the correct reference term in Fitbox. Members are unable to request for or schedule their own membership freezes through Fitbox. The member must receive an SMS or email to confirm the processing of the freeze in writing for it to be confirmed.',
      'MEMBERSHIP FREEZE FOR CLUB CLOSURES',
      'If we are required by the state or federal government to temporarily close the club, we will freeze your membership for that Closure Period. If this occurs:',
      '• You are entitled to request cancellation of your membership during the Closure Period (applicable cancellation fees will apply) but processing of the cancellation may be delayed until after the Closure Period has ended.',
      '• Please refer to section 18 regarding the terms that apply to cancellation of your membership.',
      'In addition, if the Club is closed for a period of more than one week (e.g. due to refurbishment) then you may request that your membership be frozen until the Club re-opens (Closure Period).',
      'It is important that you communicate your decision to have your membership frozen during this period when notified as Xert Fitness is not responsible for freezing your membership and will not take action to do so unless you respond to the notice and advise you would like to freeze/suspend your membership for the period.',
      'Unless the law requires otherwise, membership freezes which occur as a result of a Closure Period are not classified as a $0 payment membership fee until the club opens back up and may incur a fee of up to $5.00 per week for access to such digital workout tools as may be offered by Xert Fitness at the time through its App.',
    ],
  },
  {
    id: 'tc-25-20-membership-transfers-are-not-an-option-th',
    title: '20. MEMBERSHIP TRANSFERS ARE NOT AN OPTION THROUGH FITBOX',
    content: [
      'There is no option to transfer a membership in Fitbox therefore, Xert Fitness is unable to offer this service at this time.',
      'Members are directed to the referral program recorded on the Pre-Existing Questionnaire asking them to record the first and last name of the person whom referred them. There is a further tick box asking if the referral was part of the fiends train free Saturday’s campaign. This is to be ticked if the referral was part of this campaign. For more information on this offer see Section 11 Campaign Terms & Conditions. Friends/Guest Trains One Free Session Last Saturday of Each Month Campaign.',
      'The reward for the member who is noted down as the referred from member, will receive an offer to be determined by Xert Fitness business owner.',
    ],
  },
  {
    id: 'tc-26-21-cctv-tba',
    title: '21. CCTV - TBA',
    content: [
    ],
  },
  {
    id: 'tc-27-22-guided-training-sessions',
    title: '22. GUIDED TRAINING SESSIONS',
    content: [
      '• This offer is open to all Membership types to be guided through training exercises to help them better perform at the exercises run through in the group classes. These training sessions aim to prevent injury, make the classes easier to follow and to help members feel more confident when performing the exercises.',
      '• The monthly group coaching session shall be conducted at the end of the 8 am Sunday morning session for a further 30 minutes and is subject to the availability of the fitness professional.',
      '• Members will receive notice of this offer via the Instagram page (post, note or on the story) alternatively via SMS or an email, in relation to a confirmation of its occurrence or in the case it has been moved or if there is to be any other changes.',
      '• This offer is at no additional cost to the member',
      '• These training sessions have no cash value and cannot be exchanged, transferred or redeemed for cash.',
    ],
  },
  {
    id: 'tc-28-23-additional-safety-measures',
    title: '23. ADDITIONAL SAFETY MEASURES',
    content: [
      'Your safety and the safety of other members and our staff is of utmost importance to us and we may, from time to time, introduce reasonable health and safety measures (including for example temperature checks prior to accessing our facilities in response to COVID-19) to ensure your safety and safety of other members and our staff. If we make any reasonable health and safety measures a condition of entry and you refuse to comply with these measures, you may not be permitted to enter the Club at our discretion unless a medical exemption applies (and we are provided with appropriate supporting documents).',
    ],
  },
  {
    id: 'tc-29-24-staying-up-to-date-with-your-terms',
    title: '24. STAYING UP TO DATE WITH YOUR TERMS',
    content: [
      'We may sometimes change our terms and conditions. This includes changing the club’s opening hours, its services and facilities and membership fees. Sometimes, we may also close clubs for refurbishment. Your membership fee will be reduced or waived if the club is closed for renovations, repairs, a public holiday or another reason as put forward at the owner’s discretion. The most up-to-date terms and conditions always apply. You can find a copy on our website https://www.xertfitness.com.au/.',
      'If we reasonably consider that any change to the terms and conditions is likely to benefit you or be of no, or immaterial, detriment to you, we can make the change immediately and do not need to notify you.',
      'For all other changes, we give you at least 30 days notice of any changes, for instance by:',
      '• Publishing them in our newsletter or on our website; or',
      '• Placing a notice in the Club; or',
      '• Calling you, sending an SMS or an Email to the last email address and phone number you gave us.',
    ],
  },
  {
    id: 'tc-30-25-privacy-policy',
    title: '25. PRIVACY POLICY',
    content: [
      'Your “personal information” (as that term is defined in the Privacy Act 1988 (Cth) will only be used by Xert Fitness in accordance with the provision of their Privacy Statements. The Xert Fitness Privacy Statement can be obtained on our website XERT Fitness | Functional Training Kingaroy.',
      'MARKETING PERMISSIONS',
      'We sometimes film or photograph the Club so it is possible you will appear in the background. By signing your Agreement, you allow us to use your image in promotional and other business-related material.',
      'Xert Fitness will use the contact details you have provided above to contact you about your membership. Xert Fitness, related companies and companies we engage to perform services on our behalf, may also contact you from time to time both during and after your membership with information about fitness and wellness, promotions, special offers and other materials about Goodlife and related companies\' service and products. Xert Fitness will not provide your personal information or contact details to unrelated third parties. Depending on your preferences, you may be contacted in the following ways: mobile, @xert_fit on Instagram, email and/or SMS. You can change your mind at any time about receiving marketing materials by contacting Xert Fitness @info@xertfitness.com.au.',
    ],
  },
  {
    id: 'tc-31-26-entire-agreement',
    title: '26. ENTIRE AGREEMENT',
    content: [
      'This Agreement and its Annexures and any Special Terms & Conditions listed on the website constitute the entire agreement, understanding and arrangement (express and implied) between the Member and Xert Fitness relating to the subject matter of this Agreement and supersedes and cancels any previous agreement, understanding and arrangement relating thereto whether written or oral.',
    ],
  },
  {
    id: 'tc-32-2-key-updated-terms-and-conditions-summary',
    title: 'Annexure — 2. KEY UPDATED TERMS AND CONDITIONS SUMMARY',
    content: [
      'Third Party Payment Provider: Xert’s Third Party Payment Provider (STRIPE) has updated its terms and conditions for Xert Fitness members. Their new terms and conditions are separate to Xert Fitness membership agreement and will no longer appear on Xert Fitness website. A link to their terms and conditions is provided within XERT Fitness T&Cs and is also available here https://stripe.com/au/legal/ssa.',
    ],
  },
  {
    id: 'tc-33-3-personal-training',
    title: 'Annexure — 3. PERSONAL TRAINING',
    content: [
      'The owner will manage personal training inquiries and pass them onto the appropriate personal trainer. Members who sign up with a Personal Trainers or are already a client of the trainer, need to sign up to the Training With Personal Training Only membership or Full Access Membership. Other memberships including Casual or Three Day Pass Visit’s do not permit the Personal Training service.',
      'Members undertaking Personal Training, pay the trainer directly by an agreed payment method and payment process. Xert Fitness is not responsible for their Personal Trainers client payments or payment process or any communication between the trainer and their client.',
      'If the member has any concerns with the service they are being provided with or any other questions or points pf discussion they can contact Xert Fitness directly in relation to these such matter by emailing mailto:info@xertfitness.com.au.',
      'If Personal Trainers choose to conduct free Personal Training sessions initially as a consultation or there after for any other reason, the trainer feels appropriate, this is at the discretion of the individual Personal Trainer.',
    ],
  },
  {
    id: 'tc-34-4-terms-of-social-usage',
    title: 'Annexure — 4. TERMS OF SOCIAL USAGE',
    content: [
      'Thank you for allowing XERT Fitness to feature your content.',
      'By tagging @xert_fit, you grant Xert Fitness a worldwide, perpetual, irrevocable, royalty-free, non-exclusive license to use your personal information and content. This includes the right to reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and publicly display your content across various platforms and media. These platforms include, but are not limited to, Xert Fitness owned or operated social media platforms (whether now existing or developed in the future), digital channels, electronic communications, websites, EDMs, newsletters, banners, printed materials and marketing collateral.',
      'We collect this information strictly for the purpose of showcasing your content as outlined and do not store or use it beyond this purpose without your consent, except as required by law. By providing your consent, you also agree that Xert Fitness may store your content in accordance with our Privacy Policy. By tagging @xert_fit, you confirm that:',
      '• You are at least 18 years old.',
      '• You have the full legal right and authority to grant this license.',
      '• You hold all necessary intellectual property rights to the content.',
      '• The content does not infringe on any third-party rights, including copyright, trademark, or privacy rights.',
      '• Any individuals featured in your content have provided consent to be filmed and for the content to be reposted by XERT Fitness.',
      '• The content was created in line with Goodlife Health Club rules, policies, and staff directions, and does not depict unsafe, inappropriate, or prohibited behaviour within the club environment or by law.',
      'You, and any other individuals in the content you share with XERT Fitness also acknowledge that:',
      '• Xert Fitnesses use of your content is at our discretion, and we may choose whether or not to repost or feature your content.',
      '• Tagging @xert_fit provides permission for XERT Fitness to use your content, however, it does not automatically constitute entry into any promotion or competition unless otherwise specified as the way to enter into the competition in question.',
      '• Xert Fitness may refuse to repost or remove or request the removal of content at any time if it is deemed unsafe, offensive, misleading, if it contains footage of members who have not provided marketing consent or if the content is in breach of club policies or third-party rights.',
      '• You will not receive compensation for Xert Fitness use of your content, unless expressly stated as part of a separate promotion.',
      '• You waive any moral rights you may have in the content, to the extent permissible by law.',
      'You indemnify and hold XERT Fitness harmless from any claims, damages, or liabilities arising from Xert Fitness use of your content, including claims related to intellectual property rights and privacy. This initiative is in no way sponsored, endorsed, administered by, or associated with any social media platform. If you wish to withdraw your consent at any time, please contact us via direct message on Instagram @xert_fit, and we will take reasonable steps to remove your content from our platforms where possible. Please note that removal may not be possible in all cases (for example, where content has been included in printed materials or scheduled communications).',
    ],
  },
  {
    id: 'tc-35-5-campaign-terms-conditions',
    title: 'Annexure — 5. CAMPAIGN TERMS & CONDITIONS',
    content: [
    ],
  },
  {
    id: 'tc-36-5-1-friend-guest-trains-one-free-session-on',
    title: 'Annexure — 5.1. FRIEND/GUEST TRAINS ONE FREE SESSION ON A DAY TO BE CONFIRMED ON THE LAST WEEK OF EACH MONTH CAMPAIGN',
    content: [
      '1. Promoter - XERT Fitness ABN 65 327 079 634',
      '2. Promotional Period - From 5:15 am on the 25th of September 2026',
      '3. Promotion - Existing members can bring one friend (“Guest”)',
      '4. Eligibility',
      '• The Member wanting their friend to train for free must hold a Full Access Membership, all other Membership types including Casual, Training with Personal Trainer only and Three Day Pass are ineligible to redeem this offer',
      '• The ‘Friend’ must not already be a Full Access Member of the club',
      '• Training with a Personal Trainer memberships are eligible for the offer by way of theme selves referring themselves and taking up on the offer on the single class they have selected to attend',
      '• The ‘Friend’ cannot have already redeemed the offer before',
      '5. Exclusions - The Promotion does not provide the Guest with any ongoing free access to the gym or any other classes other than the single class they nominated',
      '6. Redemption',
      '• The ‘Friend’ is required to book the class in advance online to redeem the promotion. The friend is also able to rock up at the club and notify staff which single class they want to attend and Xert staff will have them recorded on the register.',
      '• The Pre-Exercise Questionnaire & Participant Acknowledgement must be completed prior to the friend recording their name against the class they wish to attend. Xert Fitness will SMS or email the ‘friend’ a link to complete the Pre-Exercise Questionnaire & Participant Acknowledgement prior to arrival following them pre-registering for the preferred Saturday class',
      '• The ‘Friend’ can pre-register only online via Class Timetable | XERT Fitness',
      '• To redeem the promotion, the Guest must be accompanied by the Full Access Member and sign the Pre-Exercise Questionnaire & Participant Acknowledgement at Reception or in advance (hard copy or digital) and return the hard copy or show digital proof of their consent and signature to the Xert staff member as proof of sign in. If the member has completed the PEQ via the digital link provided in advance, the Xert staff member will have this information and will not require the ‘friend’ to complete another copy',
      '• The guest must have their name recorded against the class they will attend on the nominated day by Xert Fitness on the last week of each month, when the first arrive at reception on the ‘Bring a friend free’ paperwork',
      '• The ‘Friend’ must communicate which single class they are attending on the Saturday. The offer only stands to be redeemed on a single class on this day only',
      '• Photo ID must be presented to Reception upon entry. The Xert staff member will match the signature recorded on this photo ID against the friends completed Pre-Exercise Questionnaire & Participant Acknowledgement',
      '7. Conditions',
      '• The Guest is only permitted to access the class they nominate at time of sign in.',
      '• Xert Fitness may contact the Guest (including by email, SMS, telephone or such other means) for marketing purposes of the Campaign, or the Xert Fitness brand unless the Guest opts out.',
      '8. Changes - Xert Fitness, in its sole and reasonable discretion, reserves the right to vary the Terms & Conditions of this Promotion at any time.',
      '9. Acceptance - By participating in this Promotion, you understand and accept the Terms & Conditions of this Promotion. You acknowledge and agree that upon purchasing any of the membership or visitor pass options, you will be bound by the Terms and Conditions of Xert Fitness, available: https://www.xertfitness.com.au/terms',
    ],
  },
  {
    id: 'tc-37-5-2-free-trial-group-training-session-15-8-2',
    title: 'Annexure — 5.2. Free Trial Group Training Session 15.8.26 – 29.8.26',
    content: [
      '• The “Free Pass” offer stands during the business launch period when memberships are not in place to sign up.',
      '• Prior to accessing the Club, Free Pass holders must:',
      '• Complete the Pre-Exercise Questionnaire & Participant Acknowledgement either digitally or hard copy',
      '• Have the Xert Fitness staff member sight the above documents completion',
      '• If any sections of the form have not been completed Xert Fitness staff reserve the right to ask questions in line with best practice health and safety',
      '• A Free Pass can only be used in accordance with the Xert Fitness Age Policy which restricts access and usage of certain equipment to minors. Please review the Children Policy, section 12 of this document',
      '• The Free trial pass is intended for use on the day you attend the facility',
      '• The free trial pass can be redeemed more than once',
      '• The Free Trial Pass is only intended to be used for the single session on that day offering the free training. Those who attend are required to follow the instructions of the owner and not step away and do their own thing on the equipment or in the club',
      '• This offer cannot be used in conjunction with any other offer, nor can the Free Pass be redeemed for cash.',
      '• Goodlife may contact the user of the Free Pass via email, SMS, telephone or by such other means for administrative and/or marketing purposes.',
      '• The user of the Free Pass agrees to Xert Fitnesses Terms and Conditions and accepts that their personal information will be handled in accordance with Xert Fitnesses Privacy Policy.',
    ],
  },
  {
    id: 'tc-38-5-3-xert-fitness-referral-campaign',
    title: 'Annexure — 5.3. Xert Fitness Referral Campaign',
    content: [
      '• Promoter. XERT Fitness ABN 65 327 079 634',
      '• Offer Period. From 8:00am AEST 5th September 2026 - ongoing',
      '• Promotion. Current Xert Fitness members may refer a non-member and receive a thank you gift at the discretion of the club owner.',
      '• Eligibility. The Offer will be available to current members who successfully refer one or more prospective members to purchase a membership package with Xert Fitness. Prospective members must not have been members of Xert Fitness previously, or have previously purchased a casual visit or three day pass. If the prospective member holds a Training with Personal Trainer membership and then upgrades to a Full Access membership, these such membership upgrades along with the Upfront 3 Months are not included in this referral campaign. Members who choose to do these such upgrades can do so themselves via the Fitbox app.',
      '• Redemption. When the prospective member signs up, they record the first and last name of whom referred them on the Pre Exercise Questionnaire, Risk Warning and Participant Acknowledgement. At the time the Xert staff member puts the new members details into Fitbox, they will make a record to provide the offer as agreed by the owner, on the referrer members account, or contact them to communicate the offer and when the can collect or otherwise.',
      '• Conditions. The participant confirms and warrants that they have the consent of the people they are referring to provide their details to the Promoter for the purpose of being contacted by the Promoter in relation to the Promoter’s products and services.',
      '• Changes. Xert Fitness reserves the right to vary the Terms & Conditions of this Promotion at any time at their sole and reasonable discretion.',
      '• Acceptance. By participating in this Promotion, you understand and accept the Terms & Conditions of this Promotion. Members and prospective members acknowledge and agree that upon purchasing a Membership Package through this Promotion, you will be bound by the Terms and Conditions of Xert Fitness, available at: Terms of Use | XERT Fitness',
    ],
  },
].map(Object.freeze));

/** The agreement as one plain-text block, used for the form statement blocks. */
export function termsSectionText(section) {
  return (section.content || []).join('\n\n');
}
