// Generated by scripts/build-tokens.mjs. Edit design/tokens.json.
export const kitTokens = Object.freeze({
  "table.threshold": 200,
  "table.estimate": 88,
  "table.overscan": 4,
  "filter.debounce": 250
});
