import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const tokenRoot = fileURLToPath(new URL('../', import.meta.url));
const cssName = key => key.replaceAll('.', '-');
const swiftName = key => cssName(key).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const isColor = value => /^#[\da-f]{6}(?:[\da-f]{2})?$/i.test(value);
const colorParts = value => {
  if (!isColor(value)) throw new Error(`Expected resolved color, received ${value}`);
  return [0, 2, 4, 6].map((offset, index) => index === 3 && value.length === 7 ? 255 : parseInt(value.slice(offset + 1, offset + 3), 16));
};
const hex = values => '#' + values.map(value => Math.round(value).toString(16).padStart(2, '0')).join('').toUpperCase();

export function resolveTokens(source) {
  const definitions = {};
  for (const tier of ['primitives', 'semantics', 'components']) {
    for (const [key, value] of Object.entries(source[tier] || {})) definitions[`${tier}.${key}`] = value;
  }
  for (const [key, opacities] of Object.entries(source.opacityVariants || {})) {
    for (const opacity of opacities) definitions[`semantics.${key}-${Math.round(opacity * 100)}`] = { alpha: [`{semantics.${key}}`, opacity] };
  }
  const resolved = {}, active = new Set();
  function resolveValue(value) {
    if (typeof value === 'string') return value.replace(/\{([^{}]+)\}/g, (_, ref) => visit(ref));
    const operation = value?.mix || value?.alpha;
    if (!Array.isArray(operation) || Object.keys(value).length !== 1) throw new Error('Invalid token expression');
    const amount = operation.at(-1);
    if (!Number.isFinite(amount) || amount < 0 || amount > 1) throw new Error('Color amount must be between zero and one');
    const first = colorParts(resolveValue(operation[0]));
    if (value.alpha && operation.length === 2) return hex([...first.slice(0, 3), amount * 255]);
    if (value.mix && operation.length === 3) {
      const second = colorParts(resolveValue(operation[1]));
      return hex(first.slice(0, 3).map((channel, i) => channel * (1 - amount) + second[i] * amount));
    }
    throw new Error('Invalid color operation');
  }
  function visit(key) {
    if (!Object.hasOwn(definitions, key)) throw new Error(`Invalid token reference: ${key}`);
    if (active.has(key)) throw new Error(`Token cycle: ${[...active, key].join(' -> ')}`);
    if (Object.hasOwn(resolved, key)) return resolved[key];
    const references = JSON.stringify(definitions[key]).matchAll(/\{([^{}]+)\}/g);
    for (const [, reference] of references) {
      if (key.startsWith('components.') && reference.startsWith('primitives.')) throw new Error(`Component must reference semantics: ${key}`);
      if (key.startsWith('semantics.') && reference.startsWith('components.')) throw new Error(`Semantic cannot reference component: ${key}`);
      if (key.startsWith('primitives.') && !reference.startsWith('primitives.')) throw new Error(`Primitive cannot reference another tier: ${key}`);
    }
    active.add(key);
    resolved[key] = resolveValue(definitions[key]);
    active.delete(key);
    return resolved[key];
  }
  Object.keys(definitions).sort().forEach(visit);
  return resolved;
}

export function generateTokens(source) {
  const resolved = resolveTokens(source);
  const entries = Object.entries(resolved).sort(([a], [b]) => a.localeCompare(b, 'en'));
  const semantics = entries.filter(([key]) => key.startsWith('semantics.')).map(([key, value]) => [key.slice(10), value]);
  const components = entries.filter(([key]) => key.startsWith('components.')).map(([key, value]) => [key.slice(11), value]);
  const names = [...semantics, ...components].map(([key]) => cssName(key));
  if (new Set(names).size !== names.length) throw new Error('Colliding CSS token names');
  const colors = semantics.filter(([, value]) => isColor(value));
  const declarations = [];
  for (const [key, value] of [...semantics, ...components]) {
    declarations.push(`  --${cssName(key)}: ${value};`);
    if (isColor(value)) {
      const [r, g, b, a] = colorParts(value);
      declarations.push(`  --${cssName(key)}-rgb: ${r} ${g} ${b};`, `  --${cssName(key)}-alpha: ${Number((a / 255).toFixed(6))};`);
    }
  }
  for (const [alias, key] of Object.entries(source.aliases || {})) {
    if (!resolved[`semantics.${key}`]) throw new Error(`Invalid alias ${alias}: ${key}`);
    declarations.push(`  --xert-${alias}: var(--${cssName(key)});`);
  }
  declarations.push('  --xert-radius-card: var(--card-radius);', '  --xert-radius-control: var(--radius-control);', '  --radius: var(--radius-control);');
  const durationNames = semantics.filter(([key]) => key.startsWith('duration.')).map(([key]) => `  --${cssName(key)}: 0ms;`).join('\n');
  const css = `/* Generated by scripts/build-tokens.mjs. Edit design/tokens.json. */
:root {
${declarations.join('\n')}
}
[data-density="comfortable"] { --space-row: var(--space-row-comfortable); }
[data-density="compact"] { --space-row: var(--space-row-compact); }
@media (prefers-reduced-motion: reduce) {
  :root {
${durationNames}
  }
  *, *::before, *::after {
    animation-duration: 0ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0ms !important;
    animation-delay: 0ms !important;
    scroll-behavior: auto !important;
  }
}
@media (prefers-reduced-transparency: reduce) {
  :root { --dock-blur: 0px; }
  *, *::before, *::after { backdrop-filter: none !important; -webkit-backdrop-filter: none !important; }
  .xert-glass, [data-translucent], [class*="backdrop-blur"] { background: var(--surface-overlay) !important; }
}
`;
  const twColors = Object.fromEntries(colors.map(([key]) => [cssName(key), `rgb(var(--${cssName(key)}-rgb) / calc(var(--${cssName(key)}-alpha) * <alpha-value>))`]));
  for (const [alias, key] of Object.entries(source.utilityAliases || {})) {
    if (!colors.some(([name]) => name === key)) throw new Error(`Invalid utility alias: ${alias}`);
    twColors[alias] = twColors[cssName(key)];
  }
  const color = key => twColors[cssName(key)];
  Object.assign(twColors, {
    background: color('surface.base'), foreground: color('text.primary'),
    card: { DEFAULT: color('surface.raised'), foreground: color('text.primary') },
    popover: { DEFAULT: color('surface.overlay'), foreground: color('text.primary') },
    primary: { DEFAULT: color('accent.default'), foreground: color('text.inverse') },
    secondary: { DEFAULT: color('surface.secondary'), foreground: color('text.primary') },
    muted: { DEFAULT: color('surface.sunken'), foreground: color('text.muted') },
    accent: { DEFAULT: color('accent.default'), foreground: color('text.inverse') },
    destructive: { DEFAULT: color('state.danger'), foreground: color('text.on-color') },
    border: color('border.hairline'), input: color('border.strong'), ring: color('focus.ring'),
    chart: { 1: color('chart.primary'), 2: color('chart.success'), 3: color('chart.warning'), 4: color('chart.danger'), 5: color('text.secondary') },
    sidebar: { DEFAULT: color('surface.sidebar'), foreground: color('text.secondary'), primary: color('accent.default'), 'primary-foreground': color('text.inverse'), accent: color('surface.raised'), 'accent-foreground': color('text.primary'), border: color('border.hairline'), ring: color('focus.ring') },
  });
  twColors.xert = Object.fromEntries(Object.entries(source.aliases || {}).map(([alias, key]) => [alias, twColors[cssName(key)]]));
  const tailwind = `// Generated by scripts/build-tokens.mjs. Edit design/tokens.json.\nmodule.exports = ${JSON.stringify({ colors: twColors, spacing: { row: 'var(--space-row)', 'nav-compact': 'var(--nav-height-compact)', 'nav-expanded': 'var(--nav-height-expanded)' }, transitionDuration: { quick: 'var(--duration-quick)', standard: 'var(--duration-standard)', slow: 'var(--duration-slow)' } }, null, 2)};\n`;
  const swiftColors = colors.map(([key, value]) => {
    const [r, g, b, a] = colorParts(value);
    return `    static let ${swiftName(key)} = Color(.sRGB, red: ${r}.0 / 255, green: ${g}.0 / 255, blue: ${b}.0 / 255, opacity: ${a}.0 / 255)`;
  }).join('\n');
  const swiftValues = [...semantics, ...components].filter(([, value]) => !isColor(value)).map(([key, value]) => {
    const match = value.match(/^(\d+(?:\.\d+)?)(px|rem|ms)?$/);
    if (!match) return `    static let ${swiftName(key)} = ${JSON.stringify(value)}`;
    const amount = Number(match[1]) * (match[2] === 'rem' ? 16 : match[2] === 'ms' ? 0.001 : 1);
    return `    static let ${swiftName(key)}: ${match[2] === 'ms' ? 'TimeInterval' : 'CGFloat'} = ${amount}`;
  }).join('\n');
  const nativeAliases = { xertNavy: 'surface.base', xertInk: 'surface.sidebar', xertSteel: 'accent.default', xertOffWhite: 'text.primary', xertDeep: 'surface.secondary', xertPale: 'text.secondary', xertCard: 'surface.raised', xertMuted: 'text.muted' };
  const swift = `// Generated by scripts/build-tokens.mjs. Edit design/tokens.json.\nimport SwiftUI\n\n// Dimensions use points (web rem = 16); durations use seconds.\nenum XertTokens {\n${swiftColors}\n${swiftValues}\n    static let semanticColorNames: [String] = [\n${colors.map(([key]) => `        "${key}",`).join('\n')}\n    ]\n    static func duration(_ seconds: TimeInterval, reduceMotion: Bool) -> TimeInterval { reduceMotion ? 0 : seconds }\n    static func rowSpacing(compact: Bool) -> CGFloat { compact ? spaceRowCompact : spaceRowComfortable }\n    static func dockBlur(reduceTransparency: Bool) -> CGFloat { reduceTransparency ? 0 : dockBlur }\n}\n\nextension Color {\n${Object.entries(nativeAliases).map(([name, key]) => `    static let ${name} = XertTokens.${swiftName(key)}`).join('\n')}\n}\n`;
  // CSS custom properties cannot be used in container query conditions.
  // Emit the query rules from the same component breakpoint source.
  const kitQueries = `/* Generated by scripts/build-tokens.mjs. Edit design/tokens.json. */
@container admin-kit (min-width: ${resolved['components.admin.kit.breakpoint.table']}) {
  .admin-kit-container .admin-data-table { display: table; }
  .admin-kit-container .admin-data-table thead { display: table-header-group; }
  .admin-kit-container .admin-data-table tbody { display: table-row-group; }
  .admin-kit-container .admin-data-table tr { display: table-row; }
  .admin-kit-container .admin-data-table th, .admin-kit-container .admin-data-table td { display: table-cell; }
  .admin-kit-container .admin-data-table .admin-cell-label { display: none; }
  .admin-kit-container .admin-data-table .admin-selection-heading { width: var(--admin-kit-table-selection-width); }
}
@container admin-kit (min-width: ${resolved['components.admin.kit.breakpoint.columns']}) {
  .admin-kit-container .admin-filter-controls { grid-template-columns: repeat(auto-fit, minmax(0, 1fr)); align-items: end; }
  .admin-kit-container .admin-page-header { flex-direction: row; align-items: end; justify-content: space-between; }
}
`;
  const calendarQueries = `/* Generated by scripts/build-tokens.mjs. Edit design/tokens.json. */
@container admin-kit (min-width: ${resolved['components.admin.kit.breakpoint.columns']}) {
  .calendar-editor .calendar-form-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .calendar-workspace .calendar-roster-row { flex-direction: row; align-items: center; justify-content: space-between; }
  .calendar-workspace .calendar-roster-row select { width: auto; }
}
@container admin-kit (min-width: ${resolved['components.admin.kit.breakpoint.table']}) {
  .calendar-workspace .calendar-waitlist-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .calendar-workspace .calendar-session-heading { flex-direction: row; justify-content: space-between; }
  .calendar-workspace .calendar-session-actions { max-width: 45%; }
}
@container calendar-board (min-width: ${resolved['components.admin.kit.breakpoint.table']}) {
  .calendar-board .calendar-day-cell { min-height: calc(var(--control-height) * 2); }
  .calendar-board .calendar-day-dots { display: none; }
  .calendar-board .calendar-day-details { display: flex; }
}
@container calendar-attendance (min-width: ${resolved['components.admin.kit.breakpoint.columns']}) {
  .calendar-attendance .calendar-attendance-row { grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); align-items: center; }
}
`;
  const kitNumbers = `// Generated by scripts/build-tokens.mjs. Edit design/tokens.json.\nexport const kitTokens = Object.freeze(${JSON.stringify(Object.fromEntries(['table.threshold','table.estimate','table.overscan','filter.debounce'].map(key => [key,parseFloat(resolved[`components.admin.kit.${key}`])])),null,2)});\n`;
  return { 'src/styles/tokens.css': css, 'src/styles/admin-kit-queries.css': kitQueries, 'src/styles/admin-calendar-queries.css': calendarQueries, 'src/components/admin/ui/kitTokens.mjs':kitNumbers, 'tailwind.config.tokens.cjs': tailwind, 'ios/XertFitnessApp/XertFitnessApp/Generated/XertTokens.swift': swift };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const source = JSON.parse(readFileSync(resolve(tokenRoot, 'design/tokens.json'), 'utf8'));
  for (const [path, content] of Object.entries(generateTokens(source))) {
    const target = resolve(tokenRoot, path);
    if (process.argv.includes('--check')) {
      if (readFileSync(target, 'utf8') !== content) throw new Error(`Stale generated tokens: ${path}`);
    } else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, content);
    }
  }
}
