-- Add the pre-exercise questionnaire to the Terms and Conditions waiver.
--
-- The printed XERT pre-exercise questionnaire, risk warning and participant
-- acknowledgement asks for participant details and eight YES/NO health
-- questions that must be answered before someone trains. The online form at
-- /forms/terms-and-conditions collected the acknowledgements and a signature
-- but none of the health screening, so coaches had no record of whether a
-- participant needed medical clearance.
--
-- This rewrites that form's question list to match the paper document:
--   * participant details, now including date of birth, email and address
--   * the eight pre-exercise questions, every one of them REQUIRED
--   * the clearance note shown after the questionnaire, and a declaration
--     that the answers are true, complete and accurate
--   * the existing acknowledgements and signature, unchanged
--   * an optional Friends Train Free Saturdays referral name
--
-- Existing questions keep their ids, so answers already collected still map to
-- the question that was asked. Re-running this is safe: it sets the list to a
-- fixed state rather than appending.

update public.xert_forms
   set description = 'Please complete every section and sign below. This form covers your participant '
                    || 'details, the pre-exercise questionnaire, health and safety, medical conditions, '
                    || 'your free trial day, privacy, and marketing and photography permission.',
       questions = $xertform$[
  {
    "id": "9ec24044-f7b0-58f4-811b-6928af6af070",
    "type": "section_break",
    "question": "Participant details",
    "description": "",
    "required": false,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "We need these details to keep you safe and to contact you or your emergency contact if we ever need to.",
    "skip_rules": []
  },
  {
    "id": "84703ad7-a28d-4904-9868-6c832ce38055",
    "type": "name_fields",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "question": "Your name",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "5c82d136-9308-5dd9-99e7-eb7308421522",
    "type": "date",
    "question": "Date of birth",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "e4c4e161-43e3-5462-a865-f27c411ac809",
    "type": "email",
    "question": "Email",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "you@email.com",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "5d5d7d53-d5ea-4743-8f94-22ecd5fd6ded",
    "type": "phone",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "question": "Mobile",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "",
    "placeholder": "04xx xxx xxx",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "b6e0fb34-f230-5b3d-91be-7f4892c72243",
    "type": "address",
    "question": "Address",
    "description": "Street, suburb, state and postcode.",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "c4fe2148-605d-4a3e-9dde-b7abf480ecd3",
    "type": "short_text",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "question": "Emergency contact name",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "74d53d87-5826-4055-b5e8-a1daf825852e",
    "type": "phone",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "question": "Emergency contact number",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "",
    "placeholder": "04xx xxx xxx",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "488c14d9-662f-5016-9946-8b651d807274",
    "type": "section_break",
    "question": "Pre-exercise questionnaire",
    "description": "",
    "required": false,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "Please answer YES or NO to every question. These are required \u2014 they tell your coach whether you need clearance before training.",
    "skip_rules": []
  },
  {
    "id": "49fed5d3-4830-55ec-b690-0170e5081760",
    "type": "yes_no",
    "question": "Have you ever had, or been told by a doctor that you have had, a stroke?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "7b7d7a7f-9b18-5b6d-9a91-b8de712d2702",
    "type": "yes_no",
    "question": "Has a doctor or health professional ever told you that you have a heart condition?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "c310388c-8fbe-5892-b3a7-40ac82bc378c",
    "type": "yes_no",
    "question": "Do you experience unexplained chest pain at rest or during physical activity or exercise?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "615f75e8-621a-56ab-889a-ad12a8177beb",
    "type": "yes_no",
    "question": "Do you experience faintness, dizziness or loss of balance during physical activity or exercise?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "7f22b4f2-c72e-51e8-8b58-49d5c21f3407",
    "type": "yes_no",
    "question": "Have you experienced an asthma attack requiring medical attention within the last 12 months?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "ccccb901-da9b-5ba9-8afa-039f10e0ac34",
    "type": "yes_no",
    "question": "If you have diabetes (Type 1 or Type 2), have you experienced difficulty controlling your blood glucose within the last three months?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "1f5c7987-fdb8-5b89-b328-dfc2e797fa7e",
    "type": "yes_no",
    "question": "Do you have any medical condition, injury or other health concern that may make participating in physical activity or exercise unsafe for you?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "3b0812a4-ce40-5b3c-93ef-2d9c276c81cf",
    "type": "yes_no",
    "question": "Do you have a diagnosed muscle, bone or joint condition that may be aggravated by physical activity or exercise?",
    "description": "",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "dbd8cae2-b743-50fe-9dbf-25ecf377c8b4",
    "type": "statement",
    "question": "If you answered YES to any question",
    "description": "",
    "required": false,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "XERT may require you to obtain clearance or guidance from an appropriately qualified medical or allied health professional before participating or continuing to participate in exercise. Where appropriate, you may confirm that you are currently under the supervision of a health professional who has approved your participation in an exercise program.\n\nIf you answered NO to all questions and have no other health conditions affecting your ability to exercise, you may proceed with physical activity at an appropriate intensity.",
    "skip_rules": []
  },
  {
    "id": "6e4bde0c-c478-5844-bc02-8605e8f266ec",
    "type": "single_choice",
    "question": "Pre-exercise declaration",
    "description": "I confirm that, to the best of my knowledge, the information I have provided above is true, complete and accurate.",
    "required": true,
    "hidden": false,
    "placeholder": "",
    "options": [
      "I confirm this is true, complete and accurate"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "14ca7c65-5a59-557a-a6a1-97f5151e7f7d",
    "type": "section_break",
    "question": "Risk warning & participant acknowledgement",
    "description": "",
    "required": false,
    "hidden": false,
    "placeholder": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "Participation in physical activity involves risk. Please read each item carefully before agreeing.",
    "skip_rules": []
  },
  {
    "id": "0a4db884-4374-4abf-8b48-da8cf68f15f3",
    "type": "single_choice",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "I understand and agree"
    ],
    "question": "Health and Safety",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "I understand that there is risk of injury as a result of participation in this physical exercise. I accept that I am participating at my own risk. I agree to indemnify Byron Hawley/and/or the trainer and the business Xert Fitness, for and against all liabilities to myself for personal injury.",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "30b8ccc8-e2df-4920-a479-e8e99910cc69",
    "type": "single_choice",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "I understand and agree"
    ],
    "question": "Medical Conditions",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "I confirm that I have disclosed any medical conditions that might impact you performing the exercise to the trainer and in following, to the best of my knowledge, agree that my medical conditions if any, will not hinder me from performing the exercises at hand or you will take the necessary precautions such as remove myself from the exercise if I feel shortness of breath and will take a break and inform the trainer.",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "5bd9e1d8-43d5-47f9-847a-5cc9bee24ca3",
    "type": "single_choice",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "I understand and agree"
    ],
    "question": "Free Trial Day",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "I understand that today's session is treated as a once of free access pass courtesy of Xert Fitness and that Xert Fitness is under no obligation to provide any further access or sessions without asking for payment. I am aware that signing this form isn't signing me up to a membership with Xert Fitness and that another separate New Client Sign up Form will need to be signed.",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "6f45c338-790e-4994-930a-a02d2bb4010a",
    "type": "single_choice",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "I understand and agree"
    ],
    "question": "Privacy",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "My personal information (as that term is defined in the Privacy Act 1988 (Cth)) provided below including the information provided about my emergency contact, will only be used by Xert Fitness in accordance with the provision of their Privacy Statements. The Xert Fitness Privacy Statement can be obtained from its website www.xertfitness.com.au.",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "eefcd865-5ac9-4cab-af9e-158f5c7fe605",
    "type": "yes_no",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "question": "Marketing Permission and Photography",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "Xert Fitness will be photographing the club and its members on this day and it is possible you will appear in the background. If you do not want to be featured you have disclosed this below. If this question is left unanswered Xert Fitness will act with diligence to make sure you are not featured in any marketing material. Answer Yes to allow Xert Fitness to feature you, or No if you would prefer not to be featured.",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  },
  {
    "id": "2486526d-cee2-57c1-aafc-89ccb655480c",
    "type": "short_text",
    "question": "Friends Train Free Saturdays \u2014 who referred you?",
    "description": "Optional. If you are here as part of the Friends Train Free Saturdays campaign, enter your friend's first and last name.",
    "required": false,
    "hidden": false,
    "placeholder": "First and last name",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "allow_other": false,
    "scale_min": 1,
    "scale_max": 10,
    "scale_min_label": "",
    "scale_max_label": "",
    "media_type": null,
    "media_url": "",
    "media_caption": "",
    "correct_answer": null,
    "points": 0,
    "content": "",
    "skip_rules": []
  },
  {
    "id": "576cbb02-2819-488f-a7d8-1719d8d53840",
    "type": "signature",
    "hidden": false,
    "points": 0,
    "content": "",
    "options": [
      "Option 1",
      "Option 2",
      "Option 3"
    ],
    "question": "Signature",
    "required": true,
    "media_url": "",
    "scale_max": 10,
    "scale_min": 1,
    "media_type": null,
    "skip_rules": [],
    "allow_other": false,
    "description": "By signing you confirm you have read and agree to the Terms and Conditions above.",
    "placeholder": "",
    "media_caption": "",
    "correct_answer": null,
    "scale_max_label": "",
    "scale_min_label": ""
  }
]$xertform$::jsonb,
       updated_at = now()
 where slug = 'terms-and-conditions';

do $$
begin
  if not exists (select 1 from public.xert_forms where slug = 'terms-and-conditions') then
    raise warning 'No form with slug terms-and-conditions was found; nothing was updated.';
  end if;
end;
$$;
